# Generated by Django 4.1.2 on 2024-01-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='direccion_residencia_empleador',
        ),
        migrations.AddField(
            model_name='contratos',
            name='direccion_empresa',
            field=models.CharField(default='Jenesano-Boyacá', max_length=255),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='cargo_representante',
            field=models.CharField(default='Gerente', max_length=255),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='celular_empleador',
            field=models.CharField(default='+1 (336) 899-7553', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='lugar_expedicion_cc_empleador',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='nit_empresa',
            field=models.CharField(default='901481430', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='nombre_representante',
            field=models.CharField(default='Jonathan Cifuentes', max_length=255),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='numero_documento_empleador',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='razón_social',
            field=models.CharField(default='DIGITAL BRIDGE COMMUNICATIONS WORLWIDE S.A.S', max_length=255),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='tipo_documento_empleador',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('P', 'Pasaporte')], default='CC', max_length=255),
        ),
    ]
