# Generated by Django 4.1.2 on 2024-01-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_remove_contratos_direccion_residencia_empleador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='correo_electronico_empleador',
            field=models.EmailField(default='jcifuentes@dbcw.com.co', max_length=255),
        ),
    ]
