# Generated by Django 4.1.2 on 2024-02-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contratos_correo_electronico_empleador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contratos',
            new_name='Contrato',
        ),
    ]
