# Generated by Django 4.1.2 on 2024-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_rename_contratos_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='cargo_representante',
            new_name='cargo_representante_legal',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='celular_empleador',
            new_name='celular_representante_legal',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='correo_electronico_empleador',
            new_name='correo_electronico_representante_legal',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='numero_documento_empleador',
            new_name='numero_documento_representante_legal',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='tipo_documento_empleador',
            new_name='tipo_documento_representante_legal',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='direccion_empresa',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='lugar_expedicion_cc_empleador',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nombre_representante',
        ),
        migrations.AddField(
            model_name='contrato',
            name='direccion_notificacion_judicial',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='contrato',
            name='lugar_expedicion_cc_representante_legal',
            field=models.CharField(default='Bogotá', max_length=255),
        ),
        migrations.AddField(
            model_name='contrato',
            name='nombre_representante_legal',
            field=models.CharField(default='Jonathan Cifuentes Cadena', max_length=255),
        ),
    ]
