# Generated by Django 4.1.2 on 2024-02-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_rename_cargo_representante_contrato_cargo_representante_legal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='lugar_expedicion_cc_representante_legal',
            new_name='lugar_expedicion_documento_representante_legal',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_documento_representante_legal',
            field=models.CharField(default='1016019519', max_length=20),
        ),
    ]
